spring:
  h2:
    console:
      path: /h2-console
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:weightscheduler
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8071

scheduler:
  batch-time:
    create-calender: '0 0 2 20 12 *'
    create-daily-weight: '0 0 3 20 * *'
    sync-iac-member: '0 0 3 * * *'

environment:
  inner-connect:
    iam:
      base-url: http://localhost:8061
      auth-key: 1234