spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:~/weightscheduler
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        SQL: debug

server:
  port: 8071