spring:
  datasource:
    url: jdbc:mysql://localhost:3306/WS
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8071

scheduler:
  batch-time:
    create-calender: '0 0 2 20 12 *'
    create-daily-weight: '0 0 3 20 * *'
    sync-iac-member: '0 0 3 * * *'